server:
  port: 10010
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10010/eureka/
  instance:
    appname: eureka-server
spring:
  application:
    name: eureka-server